/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as BlocksRouteImport } from './routes/blocks'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScrollBarsIndexRouteImport } from './routes/scroll-bars/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as AnimatedTestimonialsIndexRouteImport } from './routes/animated-testimonials/index'
import { Route as AnimatedCardsIndexRouteImport } from './routes/animated-cards/index'
import { Route as DocsScrollBarsRouteImport } from './routes/docs/scroll-bars'
import { Route as DocsAnimatedTestimonialsRouteImport } from './routes/docs/animated-testimonials'
import { Route as DocsAnimatedCardsRouteImport } from './routes/docs/animated-cards'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksRoute = BlocksRouteImport.update({
  id: '/blocks',
  path: '/blocks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScrollBarsIndexRoute = ScrollBarsIndexRouteImport.update({
  id: '/scroll-bars/',
  path: '/scroll-bars/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimatedTestimonialsIndexRoute =
  AnimatedTestimonialsIndexRouteImport.update({
    id: '/animated-testimonials/',
    path: '/animated-testimonials/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AnimatedCardsIndexRoute = AnimatedCardsIndexRouteImport.update({
  id: '/animated-cards/',
  path: '/animated-cards/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsScrollBarsRoute = DocsScrollBarsRouteImport.update({
  id: '/docs/scroll-bars',
  path: '/docs/scroll-bars',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsAnimatedTestimonialsRoute =
  DocsAnimatedTestimonialsRouteImport.update({
    id: '/docs/animated-testimonials',
    path: '/docs/animated-testimonials',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsAnimatedCardsRoute = DocsAnimatedCardsRouteImport.update({
  id: '/docs/animated-cards',
  path: '/docs/animated-cards',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blocks': typeof BlocksRoute
  '/components': typeof ComponentsRoute
  '/templates': typeof TemplatesRoute
  '/docs/animated-cards': typeof DocsAnimatedCardsRoute
  '/docs/animated-testimonials': typeof DocsAnimatedTestimonialsRoute
  '/docs/scroll-bars': typeof DocsScrollBarsRoute
  '/animated-cards/': typeof AnimatedCardsIndexRoute
  '/animated-testimonials/': typeof AnimatedTestimonialsIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/scroll-bars/': typeof ScrollBarsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blocks': typeof BlocksRoute
  '/components': typeof ComponentsRoute
  '/templates': typeof TemplatesRoute
  '/docs/animated-cards': typeof DocsAnimatedCardsRoute
  '/docs/animated-testimonials': typeof DocsAnimatedTestimonialsRoute
  '/docs/scroll-bars': typeof DocsScrollBarsRoute
  '/animated-cards': typeof AnimatedCardsIndexRoute
  '/animated-testimonials': typeof AnimatedTestimonialsIndexRoute
  '/docs': typeof DocsIndexRoute
  '/scroll-bars': typeof ScrollBarsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blocks': typeof BlocksRoute
  '/components': typeof ComponentsRoute
  '/templates': typeof TemplatesRoute
  '/docs/animated-cards': typeof DocsAnimatedCardsRoute
  '/docs/animated-testimonials': typeof DocsAnimatedTestimonialsRoute
  '/docs/scroll-bars': typeof DocsScrollBarsRoute
  '/animated-cards/': typeof AnimatedCardsIndexRoute
  '/animated-testimonials/': typeof AnimatedTestimonialsIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/scroll-bars/': typeof ScrollBarsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blocks'
    | '/components'
    | '/templates'
    | '/docs/animated-cards'
    | '/docs/animated-testimonials'
    | '/docs/scroll-bars'
    | '/animated-cards/'
    | '/animated-testimonials/'
    | '/docs/'
    | '/scroll-bars/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blocks'
    | '/components'
    | '/templates'
    | '/docs/animated-cards'
    | '/docs/animated-testimonials'
    | '/docs/scroll-bars'
    | '/animated-cards'
    | '/animated-testimonials'
    | '/docs'
    | '/scroll-bars'
  id:
    | '__root__'
    | '/'
    | '/blocks'
    | '/components'
    | '/templates'
    | '/docs/animated-cards'
    | '/docs/animated-testimonials'
    | '/docs/scroll-bars'
    | '/animated-cards/'
    | '/animated-testimonials/'
    | '/docs/'
    | '/scroll-bars/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlocksRoute: typeof BlocksRoute
  ComponentsRoute: typeof ComponentsRoute
  TemplatesRoute: typeof TemplatesRoute
  DocsAnimatedCardsRoute: typeof DocsAnimatedCardsRoute
  DocsAnimatedTestimonialsRoute: typeof DocsAnimatedTestimonialsRoute
  DocsScrollBarsRoute: typeof DocsScrollBarsRoute
  AnimatedCardsIndexRoute: typeof AnimatedCardsIndexRoute
  AnimatedTestimonialsIndexRoute: typeof AnimatedTestimonialsIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  ScrollBarsIndexRoute: typeof ScrollBarsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks': {
      id: '/blocks'
      path: '/blocks'
      fullPath: '/blocks'
      preLoaderRoute: typeof BlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scroll-bars/': {
      id: '/scroll-bars/'
      path: '/scroll-bars'
      fullPath: '/scroll-bars/'
      preLoaderRoute: typeof ScrollBarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animated-testimonials/': {
      id: '/animated-testimonials/'
      path: '/animated-testimonials'
      fullPath: '/animated-testimonials/'
      preLoaderRoute: typeof AnimatedTestimonialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animated-cards/': {
      id: '/animated-cards/'
      path: '/animated-cards'
      fullPath: '/animated-cards/'
      preLoaderRoute: typeof AnimatedCardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/scroll-bars': {
      id: '/docs/scroll-bars'
      path: '/docs/scroll-bars'
      fullPath: '/docs/scroll-bars'
      preLoaderRoute: typeof DocsScrollBarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/animated-testimonials': {
      id: '/docs/animated-testimonials'
      path: '/docs/animated-testimonials'
      fullPath: '/docs/animated-testimonials'
      preLoaderRoute: typeof DocsAnimatedTestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/animated-cards': {
      id: '/docs/animated-cards'
      path: '/docs/animated-cards'
      fullPath: '/docs/animated-cards'
      preLoaderRoute: typeof DocsAnimatedCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlocksRoute: BlocksRoute,
  ComponentsRoute: ComponentsRoute,
  TemplatesRoute: TemplatesRoute,
  DocsAnimatedCardsRoute: DocsAnimatedCardsRoute,
  DocsAnimatedTestimonialsRoute: DocsAnimatedTestimonialsRoute,
  DocsScrollBarsRoute: DocsScrollBarsRoute,
  AnimatedCardsIndexRoute: AnimatedCardsIndexRoute,
  AnimatedTestimonialsIndexRoute: AnimatedTestimonialsIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  ScrollBarsIndexRoute: ScrollBarsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
